### ISSUE TITLE
segfault in knn

### ISSUE THREAD

**Issue by John-Colvin** [Ravn-Tech/HyperTag#75]
running current master (d3d8300b195)

gdb stack trace:

```
0x00007ffe6418a6d7 in Index<float, float>::knnQuery_return_numpy(pybind11::object, unsigned long, int)::{lambda(unsigned long, unsigned long)#2}::operator()(unsigned long, unsigned long) const (this=0x55555980ac90, row=row@entry=0, threadId=threadId@entry=0) at bindings.cpp:315
315     bindings.cpp: No such file or directory.
(gdb) bt full
#0  0x00007ffe6418a6d7 in Index<float, float>::knnQuery_return_numpy(pybind11::object, unsigned long, int)::{lambda(unsigned long, unsigned long)#2}::operator()(unsigned long, unsigned long) const (this=0x55555980ac90, row=row@entry=0, threadId=threadId@entry=0) at bindings.cpp:315
        data = <optimized out>
        start_idx = <optimized out>
        result = std::priority_queue wrapping: std::vector of length -192, capacity 25769803593 = {<error reading variable result (Cannot access memory at address 0xc30)>
        data_numpy_l = @0x7fffffffb210: 0x5555582e4060
        data_numpy_d = @0x7fffffffb218: 0x5555586abbc0
        k = @0x7fffffffb1f8: 40
        norm_array = std::vector of length 768, capacity 768 = {-0.0656438693, -0.00188240607, 0.024570806, -0.00132345792, 0.0250285137, -0.0298759732, 0.0306670982, 0.00316128298, -0.0284196995, -0.0187344141, -0.0242117085, 0.0363302045, -0.0213107802, -0.0186562091, -0.0209287778, -0.0191882774, 0.0233381856,
          0.00579207297, -0.0691136792, -0.00609853491, 0.0187803525, -0.0146395136, -0.0138068749, 0.0181932077, 0.0265010484, 0.0328834727, 0.0109599996, -0.0108995168, -0.0538588502, -0.038510941, -0.00958266016, -0.0123666301, -0.0104721515, 0.068536438, 0.00844705012, -0.0400565453, -0.0012298777,
          0.00155452534, 0.0183192324, 0.00129542616, 0.0504850112, 0.0635909587, 0.0709769726, 0.0390915535, -0.00420415169, -0.0351894051, -0.0472720265, 0.0298247505, -0.0904107764, -0.0165663566, -0.0187629294, 0.00447256444, 0.0280851889, 0.0292292573, -0.0141723091, 0.0162908006, -0.059703283,
          -0.00156370644, -0.00643661199, 0.049946405, 0.0334154293, 0.0287730508, 0.0163538437, -0.0425121821, 0.00693678297, 0.00168456219, 0.0312860757, -0.0207320303, 0.0186786968, -0.0284498483, 0.014462023, -0.050294999, -0.0786222368, -0.00467137992, -0.00730591174, -0.00373656908, -0.0207697768,
          0.036457371, 0.0311673228, 0.00110819482, -0.0183178894, -0.0189260878, -0.0155715616, -0.0187465418, 0.00147301028, -0.0545794182, -0.0671095252, 0.0195625871, -0.0236419607, 0.0429460928, 0.047442425, -0.0551435314, -0.014894818, 0.0460909568, -0.0436526127, -0.0701980069, -0.0238671843, -0.0181005225,
          -0.0107285921, 0.0023586622, 0.0245333388, -0.0149427503, 0.00258170348, -0.0166542511, -0.0349081531, 0.0157148689, 0.027221946, 0.000511900114, -0.0220854413, 0.00104241422, -0.0679998919, -0.0417860784, 0.0270387214, 0.0649867281, -0.00174358313, 0.0174567234, -0.00848075375, 0.0265734121,
          0.0357317738, -0.021921346, -0.055617284, 0.0899901837, 0.0105315251, 0.0751143992, 0.0247911327, 0.0716819167, -0.00638728356, 0.0364727117, 0.0457414016, -0.0330321081, 0.0582752153, -0.0101318816, -0.0288470928, -0.0558135808, 0.0357543379, 0.0200881418, 0.0377327949, 0.020218417, 0.0150590744,
          0.0103015713, 0.088244088, 0.0369234011, -0.0466240346, -0.0196729153, 0.0469583608, -0.0450488739, -0.0273035206, -0.0187784862, 0.0366531126, 0.0216387268, -0.00605851645, -0.0292723831, 0.0314363725, -0.0274906158, -0.0479848012, -0.0641067401, -0.0597888455, -0.0380994976, -0.0326780826,
          0.00785975717, 0.0481747016, 0.000950561138, -0.0176460147, -0.0181128122, -0.0411796272, 0.0198744182, -0.0466705188, 0.0194101408, 0.03275159, 0.0567777753, 0.0404897071, -0.0546920411, -0.0469799712, 0.071445778, -0.0140111465, -0.0112946713, 0.0324517675, -0.0191585794, -0.0126166344, -0.0474057607,
          -0.00157130254, -0.0483237244, 0.0341237411, -0.0373514146, -0.0388341397, 0.027352469, -0.00625597592, -0.0236225352, 0.0235540867, -0.0165337138, 0.0128682218, -0.0323442556, 0.0289525893, -0.0109649915, 0.0528527834, -0.0154767036, 0.0231210813, -0.00930580404, -0.0102893002, -0.0458446592...}
        this = 0x55555980ac90
        items = @0x7fffffffb208: {<pybind11::array> = {<pybind11::buffer> = {<pybind11::object> = {<pybind11::handle> = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>},
                  m_ptr = 0x7ffff3794530}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}
#1  0x00007ffe641a0237 in ParallelFor<Index<float, float>::knnQuery_return_numpy(pybind11::object, unsigned long, int)::{lambda(unsigned long, unsigned long)#2}>(unsigned long, unsigned long, unsigned long, Index<float, float>::knnQuery_return_numpy(pybind11::object, unsigned long, int)::{lambda(unsigned long, unsigned long)#2}) (fn=..., numThreads=<optimized out>, end=<optimized out>, start=0) at bindings.cpp:26
        id = 0
#2  Index<float, float>::knnQuery_return_numpy (this=0x55555980ac90, input=..., k=<optimized out>, num_threads=<optimized out>) at bindings.cpp:309
        norm_array = std::vector of length 768, capacity 768 = {-0.0656438693, -0.00188240607, 0.024570806, -0.00132345792, 0.0250285137, -0.0298759732, 0.0306670982, 0.00316128298, -0.0284196995, -0.0187344141, -0.0242117085, 0.0363302045, -0.0213107802, -0.0186562091, -0.0209287778, -0.0191882774, 0.0233381856,
          0.00579207297, -0.0691136792, -0.00609853491, 0.0187803525, -0.0146395136, -0.0138068749, 0.0181932077, 0.0265010484, 0.0328834727, 0.0109599996, -0.0108995168, -0.0538588502, -0.038510941, -0.00958266016, -0.0123666301, -0.0104721515, 0.068536438, 0.00844705012, -0.0400565453, -0.0012298777,
          0.00155452534, 0.0183192324, 0.00129542616, 0.0504850112, 0.0635909587, 0.0709769726, 0.0390915535, -0.00420415169, -0.0351894051, -0.0472720265, 0.0298247505, -0.0904107764, -0.0165663566, -0.0187629294, 0.00447256444, 0.0280851889, 0.0292292573, -0.0141723091, 0.0162908006, -0.059703283,
          -0.00156370644, -0.00643661199, 0.049946405, 0.0334154293, 0.0287730508, 0.0163538437, -0.0425121821, 0.00693678297, 0.00168456219, 0.0312860757, -0.0207320303, 0.0186786968, -0.0284498483, 0.014462023, -0.050294999, -0.0786222368, -0.00467137992, -0.00730591174, -0.00373656908, -0.0207697768,
          0.036457371, 0.0311673228, 0.00110819482, -0.0183178894, -0.0189260878, -0.0155715616, -0.0187465418, 0.00147301028, -0.0545794182, -0.0671095252, 0.0195625871, -0.0236419607, 0.0429460928, 0.047442425, -0.0551435314, -0.014894818, 0.0460909568, -0.0436526127, -0.0701980069, -0.0238671843, -0.0181005225,
          -0.0107285921, 0.0023586622, 0.0245333388, -0.0149427503, 0.00258170348, -0.0166542511, -0.0349081531, 0.0157148689, 0.027221946, 0.000511900114, -0.0220854413, 0.00104241422, -0.0679998919, -0.0417860784, 0.0270387214, 0.0649867281, -0.00174358313, 0.0174567234, -0.00848075375, 0.0265734121,
          0.0357317738, -0.021921346, -0.055617284, 0.0899901837, 0.0105315251, 0.0751143992, 0.0247911327, 0.0716819167, -0.00638728356, 0.0364727117, 0.0457414016, -0.0330321081, 0.0582752153, -0.0101318816, -0.0288470928, -0.0558135808, 0.0357543379, 0.0200881418, 0.0377327949, 0.020218417, 0.0150590744,
          0.0103015713, 0.088244088, 0.0369234011, -0.0466240346, -0.0196729153, 0.0469583608, -0.0450488739, -0.0273035206, -0.0187784862, 0.0366531126, 0.0216387268, -0.00605851645, -0.0292723831, 0.0314363725, -0.0274906158, -0.0479848012, -0.0641067401, -0.0597888455, -0.0380994976, -0.0326780826,
          0.00785975717, 0.0481747016, 0.000950561138, -0.0176460147, -0.0181128122, -0.0411796272, 0.0198744182, -0.0466705188, 0.0194101408, 0.03275159, 0.0567777753, 0.0404897071, -0.0546920411, -0.0469799712, 0.071445778, -0.0140111465, -0.0112946713, 0.0324517675, -0.0191585794, -0.0126166344, -0.0474057607,
          -0.00157130254, -0.0483237244, 0.0341237411, -0.0373514146, -0.0388341397, 0.027352469, -0.00625597592, -0.0236225352, 0.0235540867, -0.0165337138, 0.0128682218, -0.0323442556, 0.0289525893, -0.0109649915, 0.0528527834, -0.0154767036, 0.0231210813, -0.00930580404, -0.0102893002, -0.0458446592...}
        l = {tstate = 0x55555557f6d0, disassoc = false}
        items = {<pybind11::array> = {<pybind11::buffer> = {<pybind11::object> = {<pybind11::handle> = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>},
                  m_ptr = 0x7ffff3794530}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}
        buffer = {ptr = 0x555558f8e100, itemsize = 4, size = 768, format = "f", ndim = 1, shape = std::vector of length 1, capacity 1 = {768}, strides = std::vector of length 1, capacity 1 = {4}, readonly = false, m_view = 0x555558f77000, ownview = true}
        data_numpy_l = 0x5555582e4060
        data_numpy_d = 0x5555586abbc0
        rows = 1
        features = <optimized out>
        free_when_done_l = {<pybind11::object> = {<pybind11::handle> = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x0}, <No data fields>}, <No data fields>}
        free_when_done_d = {<pybind11::object> = {<pybind11::handle> = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x55555557f6d0}, <No data fields>}, <No data fields>}
#3  0x00007ffe641a16c4 in pybind11::cpp_function::cpp_function<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}::operator()(Index<float, float>*, pybind11::object, unsigned long, int) const (
    this=<optimized out>, this=<optimized out>, args#2=<optimized out>, args#1=<optimized out>, args#0=..., c=<optimized out>) at /home/john/.cache/pypoetry/virtualenvs/hypertag-4QF0ZWLA-py3.9/lib/python3.9/site-packages/pybind11/include/pybind11/pybind11.h:84
        f = <optimized out>
        f = <optimized out>
#4  pybind11::detail::argument_loader<Index<float, float>*, pybind11::object, unsigned long, int>::call_impl<pybind11::object, pybind11::cpp_function::cpp_function<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}&, 0ul, 1ul, 2ul, 3ul, pybind11::detail::void_type>(pybind11::cpp_function::cpp_function<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}&, std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul>, pybind11::detail::void_type&&) && (f=..., this=0x7fffffffb490) at /home/john/.cache/pypoetry/virtualenvs/hypertag-4QF0ZWLA-py3.9/lib/python3.9/site-packages/pybind11/include/pybind11/cast.h:2010
No locals.
#5  pybind11::detail::argument_loader<Index<float, float>*, pybind11::object, unsigned long, int>::call<pybind11::object, pybind11::detail::void_type, pybind11::cpp_function::cpp_function<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybin--Type <RET> for more, q to quit, c to continue without paging--
d11::object, unsigned long, int)#1}&>(pybind11::cpp_function::cpp_function<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}&) && (f=..., this=0x7fffffffb490)
    at /home/john/.cache/pypoetry/virtualenvs/hypertag-4QF0ZWLA-py3.9/lib/python3.9/site-packages/pybind11/include/pybind11/cast.h:1982
No locals.
#6  pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}, pybind11::object, Index<float, float>*, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::cpp_function::initialize<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}&&, pybind11::object (*)(Index<float, float>*, pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call&) const (this=0x0, call=...) at /home/john/.cache/pypoetry/virtualenvs/hypertag-4QF0ZWLA-py3.9/lib/python3.9/site-packages/pybind11/include/pybind11/pybind11.h:184
        args_converter = {static args_pos = 0, static kwargs_pos = 0, static args_kwargs_are_last = true, static has_kwargs = false, static has_args = false, static arg_names = 746399099, argcasters = std::tuple containing = {
            [1] = {<pybind11::detail::type_caster_base<Index<float, float> >> = {<pybind11::detail::type_caster_generic> = {typeinfo = 0x5555589befa0, cpptype = 0x7ffe641b53c0 <typeinfo for Index<float, float>>, value = 0x55555980ac90}, static name = -669581275}, <No data fields>},
            [2] = {<pybind11::detail::pyobject_caster<pybind11::object>> = {value = {<pybind11::handle> = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x0}, <No data fields>}, static name = -114687963}, <No data fields>},
            [3] = {value = 40, static name = 7630441}, [4] = {value = -1, static name = 7630441}}}
        data = <optimized out>
        policy = <optimized out>
        cap = <optimized out>
        result = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = <optimized out>}
#7  pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}, pybind11::object, Index<float, float>*, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::cpp_function::initialize<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}&&, pybind11::object (*)(Index<float, float>*, pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) ()
    at /home/john/.cache/pypoetry/virtualenvs/hypertag-4QF0ZWLA-py3.9/lib/python3.9/site-packages/pybind11/include/pybind11/pybind11.h:161
No locals.
#8  0x00007ffe64195e06 in pybind11::cpp_function::dispatcher (self=<optimized out>, args_in=0x7ffe5d492bc0, kwargs_in=0x7ffe635c8e80) at /home/john/.cache/pypoetry/virtualenvs/hypertag-4QF0ZWLA-py3.9/lib/python3.9/site-packages/pybind11/include/pybind11/pybind11.h:717
        guard = {<No data fields>}
        func = @0x555558113390: {name = 0x55555859b1d0 "knn_query", doc = 0x0, signature = 0x5555586d2bc0 "(self: hnswlib.Index, data: object, k: int = 1, num_threads: int = -1) -> object", args = std::vector of length 4, capacity 4 = {{name = 0x555558315980 "self", descr = 0x0,
              value = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x0}, convert = true, none = false}, {name = 0x5555586c5e00 "data", descr = 0x0,
              value = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x0}, convert = true, none = true}, {name = 0x5555586d2b10 "k", descr = 0x5555586d1000 "1",
              value = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff7591930}, convert = true, none = true}, {name = 0x5555583212b0 "num_threads", descr = 0x5555586cb390 "-1",
              value = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff75918f0}, convert = true, none = true}},
          impl = 0x7ffe641a1580 <pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}, pybind11::object, Index<float, float>*, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::cpp_function::initialize<pybind11::object, Index<float, float>, pybind11::object, unsigned long, int, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, pybind11::arg_v>(pybind11::object (Index<float, float>::*)(pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(Index<float, float>*, pybind11::object, unsigned long, int)#1}&&, pybind11::object (*)(Index<float, float>*, pybind11::object, unsigned long, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&)>, data = {0x7ffe6419f250 <Index<float, float>::knnQuery_return_numpy(pybind11::object, unsigned long, int)>, 0x0, 0x0}, free_data = 0x0, policy = pybind11::return_value_policy::automatic, is_constructor = false, is_new_style_constructor = false, is_stateless = false, is_operator = false,
          is_method = true, has_args = false, has_kwargs = false, has_kw_only_args = false, prepend = false, nargs = 4, nargs_kw_only = 0, nargs_pos_only = 0, def = 0x5555580ec370, scope = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>},
            m_ptr = 0x555558b49750}, sibling = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff7f92680 <_Py_NoneStruct>}, next = 0x0}
        num_args = <optimized out>
        pos_args = <optimized out>
        call = {func = @0x555558113390, args = std::vector of length 4, capacity 4 = {{<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff37375b0},
            {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffe6366fcc0}, {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff7591e10},
            {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff75918f0}}, args_convert = std::vector<bool> of length 4, capacity 64 = {true, true, true, true},
          args_ref = {<pybind11::handle> = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x0}, <No data fields>},
          kwargs_ref = {<pybind11::handle> = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x0}, <No data fields>},
          parent = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff37375b0}, init_self = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>},
            m_ptr = 0x0}}
        args_to_copy = <optimized out>
        args_copied = <optimized out>
        bad_arg = false
        kwargs = {<pybind11::object> = {<pybind11::handle> = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff3782d00}, <No data fields>}, <No data fields>}
        second_pass_convert = std::vector<bool> of length 0, capacity 0
        second_pass = std::vector of length 0, capacity 0
        overloaded = false
        overloads = 0x555558113390
        it = 0x555558113390
        n_args_in = 2
        parent = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x7ffff37375b0}
        result = {<pybind11::detail::object_api<pybind11::handle>> = {<pybind11::detail::pyobject_tag> = {<No data fields>}, <No data fields>}, m_ptr = 0x1}
        self_value_and_holder = {inst = 0x0, index = 0, type = 0x0, vh = 0x0}
        append_note_if_missing_header_is_suspected = {<No data fields>}
#9  0x00007ffff7d43933 in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#10 0x00007ffff7d2957d in _PyObject_MakeTpCall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#11 0x00007ffff7d42119 in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#12 0x00007ffff7d20fa4 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#13 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#14 0x00007ffff7d313fe in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#15 0x00007ffff7d2041a in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#16 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#17 0x00007ffff7d313fe in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#18 0x00007ffff7d41eb4 in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#19 0x00007ffff7d20fa4 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#20 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#21 0x00007ffff7d313fe in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#22 0x00007ffff7d421f4 in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#23 0x00007ffff7d22abe in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#24 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#25 0x00007ffff7d313fe in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#26 0x00007ffff7d20fa4 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#27 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#28 0x00007ffff7d313fe in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#29 0x00007ffff7d201e6 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#30 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#31 0x00007ffff7d313fe in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#32 0x00007ffff7d24821 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#33 0x00007ffff7d3125a in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#34 0x00007ffff7d201e6 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#35 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#36 0x00007ffff7d1e681 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#37 0x00007ffff7de2593 in PyEval_EvalCode () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#38 0x00007ffff7de985d in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#39 0x00007ffff7d31c31 in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#40 0x00007ffff7d201e6 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#41 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#42 0x00007ffff7d313fe in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#43 0x00007ffff7d201e6 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#44 0x00007ffff7d1ecbd in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#45 0x00007ffff7d313fe in _PyFunction_Vectorcall () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#46 0x00007ffff7e0d958 in ?? () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#47 0x00007ffff7e04222 in Py_RunMain () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#48 0x00007ffff7dd5529 in Py_BytesMain () from /usr/lib/libpython3.9.so.1.0
No symbol table info available.
#49 0x00007ffff7a50b25 in __libc_start_main () from /usr/lib/libc.so.6
No symbol table info available.
#50 0x000055555555504e in _start ()
No symbol table info available.
```

**Comment by SeanPedersen** [comment]
Hmm after a quick google search it seems likely your NVIDIA drivers are misconfigured. Can you share your specs (hardware and driver version)

**Comment by John-Colvin** [comment]
My cuda setup almost certainly broken: GTX 760 running under WSL2.

Is there a way to run search cpu-only?

**Comment by SeanPedersen** [comment]
RN only for image search... will try my best to add an explicit CPU toggle for text search as well sooner than later.

**Comment by SeanPedersen** [comment]
hey just letting u know the CPU toggle has actually quiet low priority for me atm. So it may take a while... or you can look into it yourself, will try my best to help if u have Qs about the code base.
